/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author Anto
 */
public class AñadirAlumno extends javax.swing.JFrame {

    /**
     * Creates new form AñadirAlumno
     */
    public AñadirAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        agregarFoto1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        agregarFoto2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtUser1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUser3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUser4 = new javax.swing.JTextField();
        editarAlumnoBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        guardarAlumnoBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtUser5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUser6 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(17, 119, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 150));

        agregarFoto1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("AGREGAR");

        javax.swing.GroupLayout agregarFoto1Layout = new javax.swing.GroupLayout(agregarFoto1);
        agregarFoto1.setLayout(agregarFoto1Layout);
        agregarFoto1Layout.setHorizontalGroup(
            agregarFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarFoto1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        agregarFoto1Layout.setVerticalGroup(
            agregarFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarFoto1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(agregarFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, -1));

        agregarFoto2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ELIMINAR");

        javax.swing.GroupLayout agregarFoto2Layout = new javax.swing.GroupLayout(agregarFoto2);
        agregarFoto2.setLayout(agregarFoto2Layout);
        agregarFoto2Layout.setHorizontalGroup(
            agregarFoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );
        agregarFoto2Layout.setVerticalGroup(
            agregarFoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(agregarFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Grado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sexo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(17, 119, 255));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Femenino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 100, 30));

        jRadioButton2.setBackground(new java.awt.Color(17, 119, 255));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Masculino");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 30));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er grado", "2do grado", "3er grado", "4to grado", "5to grado", "6to grado", "7mo grado", "8vo grado", "9no grado", "10mo grado" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 119, 255), 2));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 270, 460));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("Apellidos");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        txtUser.setBorder(null);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        jPanel4.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 20));

        txtUser1.setBorder(null);
        txtUser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser1FocusLost(evt);
            }
        });
        jPanel4.add(txtUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(127, 127, 127));
        jLabel7.setText("Nombres");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtUser3.setBorder(null);
        txtUser3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser3FocusLost(evt);
            }
        });
        jPanel4.add(txtUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, 20));

        jLabel9.setBackground(new java.awt.Color(17, 119, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(17, 119, 255));
        jLabel9.setText("Registro de Alumno");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 20));

        txtUser4.setBorder(null);
        txtUser4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser4FocusLost(evt);
            }
        });
        jPanel4.add(txtUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 20));

        editarAlumnoBtn.setBackground(new java.awt.Color(255, 255, 255));
        editarAlumnoBtn.setForeground(new java.awt.Color(17, 119, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(17, 119, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EDITAR");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 119, 255)));

        javax.swing.GroupLayout editarAlumnoBtnLayout = new javax.swing.GroupLayout(editarAlumnoBtn);
        editarAlumnoBtn.setLayout(editarAlumnoBtnLayout);
        editarAlumnoBtnLayout.setHorizontalGroup(
            editarAlumnoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        editarAlumnoBtnLayout.setVerticalGroup(
            editarAlumnoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(editarAlumnoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        guardarAlumnoBtn.setBackground(new java.awt.Color(17, 119, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("GUARDAR");

        javax.swing.GroupLayout guardarAlumnoBtnLayout = new javax.swing.GroupLayout(guardarAlumnoBtn);
        guardarAlumnoBtn.setLayout(guardarAlumnoBtnLayout);
        guardarAlumnoBtnLayout.setHorizontalGroup(
            guardarAlumnoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        guardarAlumnoBtnLayout.setVerticalGroup(
            guardarAlumnoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(guardarAlumnoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 130, 30));

        jSeparator1.setBackground(new java.awt.Color(17, 119, 255));
        jSeparator1.setForeground(new java.awt.Color(17, 119, 255));
        jSeparator1.setToolTipText("");
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 290, 10));

        jSeparator2.setBackground(new java.awt.Color(17, 119, 255));
        jSeparator2.setForeground(new java.awt.Color(17, 119, 255));
        jSeparator2.setToolTipText("");
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, 10));

        jSeparator3.setBackground(new java.awt.Color(17, 119, 255));
        jSeparator3.setForeground(new java.awt.Color(17, 119, 255));
        jSeparator3.setToolTipText("");
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, 10));

        jSeparator4.setBackground(new java.awt.Color(17, 119, 255));
        jSeparator4.setForeground(new java.awt.Color(17, 119, 255));
        jSeparator4.setToolTipText("");
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 10));

        jSeparator5.setBackground(new java.awt.Color(17, 119, 255));
        jSeparator5.setForeground(new java.awt.Color(17, 119, 255));
        jSeparator5.setToolTipText("");
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(127, 127, 127));
        jLabel13.setText("C.I");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtUser5.setBorder(null);
        txtUser5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser5FocusLost(evt);
            }
        });
        jPanel4.add(txtUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, 20));

        jComboBox1.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 119, 255), 2));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, 50, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(127, 127, 127));
        jLabel14.setText("Dirección");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(127, 127, 127));
        jLabel8.setText("Fecha Nacimiento");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        txtUser6.setBorder(null);
        txtUser6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser6FocusLost(evt);
            }
        });
        jPanel4.add(txtUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 20));

        jSeparator6.setBackground(new java.awt.Color(17, 119, 255));
        jSeparator6.setForeground(new java.awt.Color(17, 119, 255));
        jSeparator6.setToolTipText("");
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(127, 127, 127));
        jLabel15.setText("Telefono");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(127, 127, 127));
        jLabel19.setText("Email");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 470));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUser5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser5FocusLost

    private void txtUser5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser5FocusGained

    private void txtUser4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser4FocusLost

    private void txtUser4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser4FocusGained

    private void txtUser3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser3FocusLost

    private void txtUser3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser3FocusGained

    private void txtUser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser1FocusLost

    private void txtUser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser1FocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
        if ("".equals(txtUser.getText())) {
            txtUser.setText("Correo Electronico");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
        txtUser.setText("");
    }//GEN-LAST:event_txtUserFocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtUser6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser6FocusGained

    private void txtUser6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser6FocusLost

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarFoto1;
    private javax.swing.JPanel agregarFoto2;
    private javax.swing.JPanel editarAlumnoBtn;
    private javax.swing.JPanel guardarAlumnoBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser1;
    private javax.swing.JTextField txtUser3;
    private javax.swing.JTextField txtUser4;
    private javax.swing.JTextField txtUser5;
    private javax.swing.JTextField txtUser6;
    // End of variables declaration//GEN-END:variables
}
